const projects = [
  {slug:'smiley-co', title:'Smiley Co', client:'Smilecorp Ltd', discipline:'Brand / Campaign / Film', tone:'blue'},
  {slug:'circular', title:'Circular', client:'Circular Health', discipline:'Brand / Digital / Motion', tone:'pink'},
  {slug:'ode-studio', title:'ODE Studio', client:'Coda', discipline:'Brand / Digital / Visual System', tone:'yellow'},
  {slug:'deadpan-supply', title:'Deadpan Supply', client:'Deadpan Supply Company', discipline:'Brand / Packaging / Digital', tone:'lav'},
  {slug:'orbita', title:'Orbita', client:'Orbita Collective Plc', discipline:'Brand / Digital / Visual System', tone:'green'},
  {slug:'avant-gallery', title:'Avant Gallery', client:'Avant Collective', discipline:'Brand / Campaign / Art Direction', tone:'purple'},
  {slug:'grindline', title:'Grindline', client:'Grindline Co.', discipline:'Brand / Digital / Motion', tone:'orange'}
];
const services = ['Mobile Design','UX & Product Design','Identity & Branding','Illustration','Web Development','Shopify Integration','Digital Solutions','Campaign Films','Motion Design','Creative Direction'];
const socials = [['Instagram','https://www.instagram.com/'],['Threads','https://www.threads.net/'],['Behance','https://www.behance.net/myselfakumar'],['LinkedIn','https://www.linkedin.com/in/kumaramannn/']];
const steps = [
 ['01','Problem Framing','Understand the brief, audience, context and ambition before anything becomes visible.'],
 ['02','Shaping the Idea','Turn strategy into a clear visual direction that can hold across identity, digital, motion and film.'],
 ['03','Testing the Experience','Build, test and iterate the system across the places where people will actually encounter it.'],
 ['04','Polishing the Outcome','Refine the details, remove friction and deliver a coherent final system ready for real use.']
];
const posts = [
 ['Design & direction','Ideas made visible.','Brand worlds, digital experiences, films and visual systems built around a clear creative point of view.'],
 ['Visual storytelling','Made to be remembered.','Moving between strategy, design, motion and film until the idea has a language of its own.'],
 ['Independent practice','The medium changes.','The obsession with making it feel right does not.']
];
const app = document.getElementById('app');
const esc = s => String(s).replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function header(){return `<header class="site-header"><div class="nav-shell"><a class="brand" href="/">Kumar Aman</a><nav class="desktop-nav"><a href="/work">Work</a><a href="/#about">About</a><a href="/#experience">Experience</a><a href="/contact">Contact</a></nav><div class="header-right"><a class="social-btn" href="https://www.instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram">ig</a><button class="menu-btn" aria-expanded="false" aria-label="Open menu">Menu</button></div><div class="mobile-panel"><a href="/work">Work</a><a href="/#about">About</a><a href="/#experience">Experience</a><a href="/contact">Contact</a><span>Based in India<br>Available Worldwide</span></div></div></header>`}
function footer(){return `<footer class="contact"><div class="contact-wrap"><div class="contact-main reveal"><div class="contact-icon">KA</div><div class="contact-copy"><h2>Let's talk about your project.</h2><p>Got a project in mind? Let's create something great. We can transform that idea into real work.</p><a class="contact-mail" href="mailto:work@kumaraman.pro">work@kumaraman.pro <span>↗</span></a><div class="contact-tag">and make it real together</div></div></div><div class="footer-bottom"><span>© 2026 Kumar Aman</span><div class="footer-links">${socials.map(([n,u])=>`<a href="${u}" target="_blank" rel="noreferrer">${esc(n)}</a>`).join('')}</div></div></div></footer>`}
function hero(){return `<section class="hero"><div class="hero-inner"><div class="hero-top"><h1 class="hello">Hello!</h1><div class="portrait-stack" aria-hidden="true"><div class="portrait"><div class="face">KA</div></div><div class="portrait"><div class="face">KA</div></div><div class="portrait active"><div class="face"><span>Kumar Aman</span></div></div></div><h1 class="hero-name">I'm Kumar,</h1></div><h1 class="hero-title">a creative director.</h1><p class="hero-copy">Creative direction for <strong>brands</strong>, <strong>campaigns</strong> and cultural storytelling across <strong>film</strong>, <strong>design</strong> and <strong>digital media</strong>.</p></div><div class="hero-badges"><div class="badge left">Brand &amp; Film</div><div class="badge right">Creative Direction</div><div class="scribble one"></div><div class="scribble two"></div></div></section>`}
function infoCards(){const cards=[['My Portfolio','Explore selected projects and the work I have made across brand, film, design and digital.','/work','↗'],['About Me','A closer look at the practice, experience and thinking behind the work.','/#about','↗'],['Contact Me','Let’s work together to bring your ideas and vision to life.','/contact','↗']];return `<section class="info-section"><div class="info-container"><div class="info-grid">${cards.map((c,i)=>`<a class="info-card reveal" href="${c[2]}"><div class="info-icon">${['✳','◌','↗'][i]}</div><h3>${c[0]}</h3><p>${c[1]}</p><span class="circle-arrow">${c[3]}</span></a>`).join('')}</div></div></section>`}
function projectCard(p,i){return `<article class="project-card reveal" data-route="/work/${p.slug}"><div class="project-visual ${p.tone}"><span class="project-art-label">${esc(p.client)}</span><span class="project-number">${String(i+1).padStart(2,'0')}</span><strong class="project-name-art">${esc(p.title)}</strong></div><div class="project-info"><span class="eyebrow">Selected work</span><h3>${esc(p.title)}</h3><div class="project-meta"><span>${esc(p.client)}</span><span>·</span><span>${esc(p.discipline)}</span></div><p>${projectDescription(p)}</p><span class="pill">View Project <span>↗</span></span></div></article>`}
function projectDescription(p){const d={'smiley-co':'Creative direction, brand expression and campaign thinking shaped around a playful, recognisable visual world.','circular':'A visual system bringing brand, digital and motion together with clarity and a strong sense of consistency.','ode-studio':'A considered identity and visual language designed to move naturally across digital touchpoints.','deadpan-supply':'Brand, packaging and digital direction built as one coherent system rather than separate deliverables.','orbita':'A visual framework connecting identity, digital expression and a contemporary brand point of view.','avant-gallery':'Art direction and campaign thinking developed to give the brand a distinctive cultural presence.','grindline':'Brand and motion direction built around a sharp, flexible visual system.'};return d[p.slug] || ''}
function workSection(){return `<section class="section" id="work"><div class="section-inner"><div class="section-head reveal"><h2>My selected works</h2><p>Creative direction for brands, campaigns and cultural storytelling, moving between design, motion and film.</p></div><div class="projects">${projects.slice(0,4).map(projectCard).join('')}</div><div class="more reveal"><h3>Are you ready to see more?</h3><a class="pill" href="/work">See All Works <span>↗</span></a></div></div></section>`}
function testimonial(){return `<section class="testimonial"><div class="testimonial-inner reveal"><blockquote class="quote">“Kumar brings cinematic clarity to brand storytelling. His direction balances visual craft with strategic thinking, resulting in campaigns that resonate deeply.”</blockquote><div class="quote-meta"><strong>Creative Lead</strong><span>Global Brand Campaign</span></div></div></section>`}
function processSection(){return `<section class="process" id="experience"><div class="section-inner"><div class="process-top"><div class="process-intro reveal"><h2>High-quality work with real value considered.</h2><p>My working process revolves around an approach aimed at maximizing productivity and creativity with clarity and focus.</p><a class="pill" href="/contact">Learn More <span>↗</span></a></div><div class="steps">${steps.map(s=>`<article class="step reveal"><span class="step-num">(${s[0]})</span><div><h3>${s[1]}</h3><p>${s[2]}</p></div></article>`).join('')}</div></div><div class="facts reveal"><div class="facts-head"><h3>My numbers say it all</h3><p>Experience, consistency and measurable impact built through years of making work across disciplines.</p></div><div class="fact-grid"><div class="fact"><strong>495+</strong><span>Projects</span></div><div class="fact"><strong>7+</strong><span>Years of practice</span></div><div class="fact"><strong>MTV</strong><span>India feature</span></div><div class="fact"><strong>ELLE</strong><span>India publication</span></div><div class="fact"><strong>∞</strong><span>Ways to make it better</span></div></div></div></div></section>`}
function aboutSection(){return `<section class="about" id="about"><div class="about-wrap"><div class="about-main"><div class="availability-card reveal"><div class="availability-ring">I AM AVAILABLE<br>FOR FREELANCE</div></div><div class="about-copy reveal"><h2>Hey! That’s me.</h2><p>I am Kumar Aman, a Creative Director and filmmaker working across brand, design, motion and film. I build visual systems that connect strategy, storytelling and culture.</p><p>From a brand identity to a campaign, a website to a cinematic film, the medium changes. The obsession with making it feel right does not.</p><div class="skills"><span class="skill">Creative Direction</span><span class="skill">Brand Design</span><span class="skill">Film</span><span class="skill">Motion</span><span class="skill">Digital</span></div></div></div><div class="capabilities"><div class="capabilities-head reveal"><h3>My capabilities</h3><p>The services I bring together across strategy, identity, digital, motion and production.</p></div><div class="service-grid">${services.map(s=>`<span class="service reveal">${esc(s)}</span>`).join('')}</div></div></div></section>`}
function blogSection(){return `<section class="section blog"><div class="section-inner"><div class="section-head reveal"><h2>From the practice</h2><p>Notes from an independent creative practice moving between brand, design, film and digital.</p></div><div class="blog-grid">${posts.map((p,i)=>`<article class="post reveal"><small>0${i+1} · ${p[0]}</small><h3>${p[1]}</h3><p>${p[2]}</p></article>`).join('')}</div></div></section>`}
function home(){return `${header()}<main>${hero()}${infoCards()}${workSection()}${testimonial()}${processSection()}${aboutSection()}${blogSection()}</main>${footer()}`}
function workPage(){return `${header()}<main><section class="page-hero"><div class="page-hero-inner"><small>Selected work</small><h1>Some of my favourite work.</h1></div></section><section class="section"><div class="section-inner"><div class="projects">${projects.map(projectCard).join('')}</div></div></section></main>${footer()}`}
function projectPage(p){return `${header()}<main><section class="detail-hero"><div class="detail-inner"><small>0${projects.indexOf(p)+1} / Selected work</small><h1>${esc(p.title)}</h1><p>${esc(p.client)}</p></div></section><section class="detail-content"><div class="detail-grid"><div class="detail-copy reveal"><h2>${esc(p.discipline)}</h2><p>${projectDescription(p)}</p><p>This page uses the same project-detail system as the reference site, with the project identity and information belonging to Kumar Aman.</p><a class="pill back" href="/work">← Back to work</a></div><div class="detail-art ${p.tone} reveal"><span class="project-art-label">${esc(p.client)}</span><strong class="project-name-art">${esc(p.title)}</strong></div></div></section></main>${footer()}`}
function contactPage(){return `${header()}<main><section class="page-hero"><div class="page-hero-inner"><small>Contact</small><h1>Let’s make something worth remembering.</h1></div></section><section class="section"><div class="section-inner"><div class="section-head reveal"><h2>Have a problem worth solving?</h2><p>For creative direction, brand systems, films, motion and digital work.</p><a class="pill" href="mailto:work@kumaraman.pro">work@kumaraman.pro <span>↗</span></a></div></div></section></main>${footer()}`}
function render(){const path=window.location.pathname.replace(/\/$/,'')||'/';const project=projects.find(p=>path===`/work/${p.slug}`);app.innerHTML=project?projectPage(project):path==='/work'?workPage():path==='/contact'?contactPage():home();document.title=project?`${project.title} | Kumar Aman`:path==='/work'?'Work | Kumar Aman':path==='/contact'?'Contact | Kumar Aman':'Kumar Aman | Creative Director & Filmmaker';bind();observe()}
function bind(){document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',()=>{history.pushState({},'',el.dataset.route);render();window.scrollTo({top:0,behavior:'instant'})}));const menu=document.querySelector('.menu-btn');const panel=document.querySelector('.mobile-panel');if(menu){menu.addEventListener('click',()=>{const open=panel.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Close':'Menu'});panel.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{panel.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menu'}))}}
function observe(){const els=document.querySelectorAll('.reveal');if(!('IntersectionObserver' in window)){els.forEach(e=>e.classList.add('in'));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>io.observe(e))}
window.addEventListener('popstate',()=>{render();window.scrollTo(0,0)});render();
