const projects=[
 {slug:'smiley-co',title:'Smiley Co',client:'Smilecorp Ltd',category:'Brand / Campaign / Film',tone:'blue',desc:'Creative direction, brand expression and campaign thinking shaped around a playful, recognisable visual world.'},
 {slug:'circular',title:'Circular',client:'Circular Health',category:'Brand / Digital / Motion',tone:'pink',desc:'A visual system bringing brand, digital and motion together with clarity and a strong sense of consistency.'},
 {slug:'ode-studio',title:'ODE Studio',client:'Coda',category:'Brand / Digital / Visual System',tone:'yellow',desc:'A considered identity and visual language designed to move naturally across digital touchpoints.'},
 {slug:'deadpan-supply',title:'Deadpan Supply',client:'Deadpan Supply Company',category:'Brand / Packaging / Digital',tone:'lav',desc:'Brand, packaging and digital direction built as one coherent system rather than separate deliverables.'},
 {slug:'orbita',title:'Orbita',client:'Orbita Collective Plc',category:'Brand / Digital / Visual System',tone:'green',desc:'A visual framework connecting identity, digital expression and a contemporary brand point of view.'}
];
const services=['Mobile Design','UX & Product Design','Identity & Branding','Illustration','Web Development','Shopify Integration','Digital Solutions'];
const socials=[['Instagram','https://www.instagram.com/framedbyaman/'],['Threads','https://www.threads.net/'],['Behance','https://www.behance.net/myselfakumar'],['LinkedIn','https://www.linkedin.com/in/kumaramannn/']];
const steps=[
 ['01','Problem Framing','I explore insights and market context to clearly define the problem. Research findings are translated into ideas that shape direction, inform decisions, and establish a strong foundation for the project.'],
 ['02','Shaping the Idea','Here, I refine initial ideas into clear concepts by aligning strategy and creativity. I develop structural directions that balance innovation with feasibility, while supporting both brand goals and user expectations.'],
 ['03','Testing the Experience','In this phase, I bring concepts to life through prototyping and real-world testing. I validate functionality, usability, and clarity by iterating on feedback, refining details, and resolving issues before final delivery.'],
 ['04','Polishing the Outcome','In the final stage, thorough attention is given to refine the product, ensuring it meets high standards of quality and functionality through testing, tweaking, and iteration to address any remaining issues.']
];
const posts=[
 ['Design choices that age well and the ones you will regret later.','Useful takeaways for product and web design work. From layout rhythm to final finishing touches.','Feb 7, 2026'],
 ['Small design decisions that quietly change the entire experience.','A curated mix of patterns I return to often. Use them to improve clarity, consistency, and flow.','Feb 7, 2026'],
 ['Design choices that age well and the ones you will regret later.','Useful takeaways for product and web design work. From layout rhythm to final finishing touches.','Feb 7, 2026']
];
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function header(){return `<header class="site-header"><div class="nav-shell"><a class="brand" href="/">Kumar Aman</a><nav class="desktop-nav"><a href="/">Home</a><a href="/work">Work</a><a href="/#about">About</a><a href="/#experience">Experience</a><a href="/contact">Contact</a></nav><div class="header-right"><a class="social-btn" href="https://www.instagram.com/framedbyaman/" target="_blank" rel="noreferrer" aria-label="Instagram">ig</a><button class="menu-btn" aria-expanded="false" aria-label="Open menu"><span></span><span></span></button></div><div class="mobile-panel"><a href="/">Home</a><a href="/work">Work</a><a href="/#about">About</a><a href="/#experience">Experience</a><a href="/contact">Contact</a></div></div></header>`}
function hero(){return `<section class="hero"><div class="hero-inner"><div class="hero-top"><h1 class="hello">Hello!</h1><div class="portrait-stack" aria-hidden="true"><div class="portrait p1"><span>KA</span></div><div class="portrait p2"><span>KA</span></div><div class="portrait p3"><span>Kumar Aman</span></div></div><h1 class="hero-name">I'm Kumar,</h1></div><h1 class="hero-title">a creative director.</h1><p class="hero-copy">Creative direction for <strong>brands</strong>, <strong>campaigns</strong> and cultural storytelling across <strong>film</strong>, <strong>design</strong> and <strong>digital media</strong>.</p><div class="hero-decor decor-left"><span>Brand &amp; Film</span></div><div class="hero-decor decor-right"><span>Creative Direction</span></div><div class="hero-doodle doodle-left"></div><div class="hero-doodle doodle-right"></div></div></section>`}
function infoCards(){const cards=[['My Portfolio','Explore selected projects and my approach to creative direction.','/work','↗'],['About Me','A closer look at my background, skills, and creative journey.','/#about','↗'],['Contact Me','Let’s work together to bring your ideas and vision to life.','/contact','↗']];return `<section class="info-section"><div class="info-bg"></div><div class="info-container"><div class="info-grid">${cards.map((c,i)=>`<a class="info-card reveal card-${i+1}" href="${c[2]}"><div class="info-icon">${['✦','◌','↗'][i]}</div><div class="info-copy"><h3>${c[0]}</h3><p>${c[1]}</p></div><span class="circle-arrow">${c[3]}</span></a>`).join('')}</div></div></section>`}
function projectCard(p,i){return `<article class="project-card reveal" data-route="/work/${p.slug}"><div class="project-visual ${p.tone}"><div class="visual-grid"></div><div class="visual-orbit"></div><div class="visual-window"><span>${String(i+1).padStart(2,'0')}</span></div><span class="project-art-label">${esc(p.client)}</span><strong class="project-name-art">${esc(p.title)}</strong></div><div class="project-info"><div class="project-title"><h2>${esc(p.title)}</h2><span>${esc(p.category)}</span></div><p>${esc(p.desc)}</p><span class="pill">View Project <span>↗</span></span></div></article>`}
function workSection(){return `<section class="section work-section" id="work"><div class="wide-container"><div class="section-head reveal"><h2>My selected works</h2><p>Creative direction for brands, campaigns and cultural storytelling across design, motion and film.</p></div><div class="projects">${projects.slice(0,4).map(projectCard).join('')}</div><div class="more reveal"><p>Are you ready to see more?</p><a class="pill" href="/work">See All Works <span>↗</span></a></div></div></section>`}
function testimonial(){return `<section class="testimonial"><div class="testimonial-inner reveal"><div class="quote-mark">“</div><blockquote>From the very beginning the collaboration felt effortless. Every idea was carefully refined into something meaningful, and the final result was exactly what we hoped for.</blockquote><div class="quote-author"><strong>Creative Lead</strong><span>Global Brand Campaign</span></div></div></section>`}
function processSection(){return `<section class="process" id="experience"><div class="section-inner process-inner"><div class="process-top"><div class="process-intro reveal"><h2>High-quality work with real value considered.</h2><p>My working process revolves around an approach aimed at maximizing productivity and creativity with clarity and focus. It begins with thorough research and planning, where I gather relevant information and outline key objectives.</p><a class="pill" href="/contact">Learn More <span>↗</span></a></div><div class="steps">${steps.map(s=>`<article class="step reveal"><span class="step-num">(${s[0]})</span><div><h3>${s[1]}</h3><p>${s[2]}</p></div></article>`).join('')}</div></div><div class="facts"><div class="facts-head reveal"><h2>My numbers say it all</h2><p>These numbers reflect the <strong>experience</strong> and <strong>consistency</strong>, and measurable impact behind the work I’ve delivered over the years.</p></div><div class="fact-grid">${[['495+','Projects completed'],['7+','Years of practice'],['MTV','India feature'],['ELLE','India publication'],['45','Countries and cities explored']].map(x=>`<div class="fact reveal"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}</div></div></div></section>`}
function aboutSection(){return `<section class="about" id="about"><div class="about-wrap"><div class="about-main"><div class="about-media reveal"><div class="about-photo"><span>KA</span></div><div class="availability-ring">– I AM AVAILABLE –<br>FOR FREELANCE</div></div><div class="about-copy reveal"><h2>Hey! That’s me.</h2><p>I am Kumar Aman, a multidisciplinary creative director and filmmaker based in India. With a keen eye for aesthetics and a knack for innovative solutions, I work across the dynamic intersection of brand, design, motion and film.</p><p>My journey in this dynamic and ever-evolving field has been a testament to my unwavering passion for meticulously crafting meaningful visual experiences, leveraging technology, and fearlessly pushing the boundaries of creative storytelling.</p></div></div><div class="capabilities"><div class="capabilities-head reveal"><h2>My capabilities</h2><p>The services I offer are meticulously crafted and tailored to cater specifically to your <strong>unique needs</strong> and <strong>requirements</strong>.</p></div><div class="service-grid">${services.map(s=>`<span class="service reveal">${esc(s)}</span>`).join('')}</div></div></div></section>`}
function blogSection(){return `<section class="blog"><div class="blog-inner"><div class="blog-head reveal"><h2>From the blog</h2><p>Here I share insights as a freelancer, offering valuable <strong>tips</strong>, <strong>tricks</strong>, and <strong>experiences</strong> on navigating the creative landscape.</p></div><div class="blog-grid">${posts.map((p,i)=>`<article class="post reveal"><div class="post-image"><span>${String(i+1).padStart(2,'0')}</span></div><div class="post-inner"><div class="post-text"><h3>${p[0]}</h3><p>${p[1]}</p></div><div class="post-footer"><span>${p[2]}</span><span class="post-dot">·</span><span>${i===1?'Illustration':'Design'}</span></div></div></article>`).join('')}</div><a class="pill blog-more" href="/work">See All Posts <span>↗</span></a></div></section>`}
function footer(){return `<footer class="contact"><div class="contact-wrap"><div class="contact-main reveal"><div class="contact-icon">✉</div><div class="contact-copy"><h2>Contact Me</h2><p>Let’s work together to bring your ideas and vision to life.</p><a class="contact-mail" href="mailto:work@kumaraman.pro">work@kumaraman.pro <span>↗</span></a></div></div><div class="footer-bottom"><span>© 2026 Kumar Aman</span><div class="footer-links">${socials.map(([n,u])=>`<a href="${u}" target="_blank" rel="noreferrer">${esc(n)}</a>`).join('')}</div></div></div></footer>`}
function home(){return `${header()}<main>${hero()}${infoCards()}${workSection()}${testimonial()}${processSection()}${aboutSection()}${blogSection()}</main>${footer()}`}
function workPage(){return `${header()}<main><section class="page-hero"><div class="page-hero-inner"><small>Selected work</small><h1>Some of my favourite work.</h1></div></section><section class="section work-page"><div class="wide-container"><div class="projects">${projects.map(projectCard).join('')}</div></div></section></main>${footer()}`}
function projectPage(p){return `${header()}<main><section class="detail-hero"><div class="detail-inner"><small>${String(projects.indexOf(p)+1).padStart(2,'0')} / Selected work</small><h1>${esc(p.title)}</h1><p>${esc(p.client)}</p></div></section><section class="detail-content"><div class="detail-grid"><div class="detail-copy reveal"><h2>${esc(p.category)}</h2><p>${esc(p.desc)}</p><p>Creative direction, visual language and production thinking are brought together here as one coherent project system.</p><a class="pill" href="/work">← Back to work</a></div><div class="detail-art ${p.tone} reveal"><div class="visual-grid"></div><div class="visual-orbit"></div><div class="visual-window"><span>PROJECT</span></div><strong class="project-name-art">${esc(p.title)}</strong></div></div></section></main>${footer()}`}
function contactPage(){return `${header()}<main><section class="page-hero"><div class="page-hero-inner"><small>Contact</small><h1>Let’s work together to bring your ideas and vision to life.</h1></div></section><section class="section"><div class="section-inner"><div class="section-head reveal"><h2>Have a project in mind?</h2><p>Creative direction, brand systems, films, motion and digital experiences.</p><a class="pill" href="mailto:work@kumaraman.pro">work@kumaraman.pro <span>↗</span></a></div></div></section></main>${footer()}`}
function render(){const path=window.location.pathname.replace(/\/$/,'')||'/';const project=projects.find(p=>path===`/work/${p.slug}`);app.innerHTML=project?projectPage(project):path==='/work'?workPage():path==='/contact'?contactPage():home();document.title=project?`${project.title} | Kumar Aman`:path==='/work'?'Work | Kumar Aman':path==='/contact'?'Contact | Kumar Aman':'Kumar Aman | Creative Director';bind();observe()}
function bind(){document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();history.pushState({},'',el.dataset.route);render();window.scrollTo(0,0)}));const menu=document.querySelector('.menu-btn'),panel=document.querySelector('.mobile-panel');if(menu){menu.addEventListener('click',()=>{const open=panel.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});panel.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{panel.classList.remove('open');menu.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}))}}
function observe(){const els=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('in'));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -5% 0px'});els.forEach(e=>io.observe(e))}
window.addEventListener('popstate',()=>{render();window.scrollTo(0,0)});render();
