const projects=[
 {slug:'smiley-co',title:'Smiley Co',client:'Smilecorp Ltd',discipline:'Brand / Campaign / Film',tone:'lavender'},
 {slug:'circular',title:'Circular',client:'Circular Health',discipline:'Brand / Digital / Motion',tone:'mint'},
 {slug:'ode-studio',title:'ODE Studio',client:'Coda',discipline:'Brand / Digital / Visual System',tone:'peach'},
 {slug:'deadpan-supply',title:'Deadpan Supply',client:'Deadpan Supply Company',discipline:'Brand / Packaging / Digital',tone:'yellow'}
]
const capabilities=['Brand Identity','Digital Design','Motion Design','Film & Production','Art Direction','Creative Strategy']
const process=[['01','Frame the idea','Understand the problem, context and ambition before making anything visible.'],['02','Shape the direction','Turn strategy into a clear visual language across brand, digital, motion and film.'],['03','Make it move','Develop the work through design, direction, production and iteration.'],['04','Refine the outcome','Polish every detail until the system feels coherent, useful and unmistakably itself.']]
const socials=[['Instagram','https://www.instagram.com/'],['LinkedIn','https://www.linkedin.com/'],['Behance','https://www.behance.net/myselfakumar']]
const app=document.getElementById('app')
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))
function header(){return `<header class="site-header"><a class="brand" href="/">Kumar Aman</a><nav class="desktop-nav"><a href="/#work">Work</a><a href="/#about">About</a><a href="/#experience">Experience</a><a href="/#contact">Contact</a></nav><div class="availability">Based in India <span>•</span> Available Worldwide</div><button class="menu-btn" aria-label="Toggle menu" aria-expanded="false">Menu</button><div class="mobile-menu"><a href="/#work">Work</a><a href="/#about">About</a><a href="/#experience">Experience</a><a href="/#contact">Contact</a><span>Based in India<br>Available Worldwide</span></div></header>`}
function footer(){return `<footer class="footer"><div><strong>Kumar Aman</strong><a href="mailto:madebykraman@gmail.com">madebykraman@gmail.com</a></div><div class="footer-nav"><a href="/">Home</a><a href="/work">Work</a><a href="/#about">About</a><a href="/#contact">Contact</a></div><div class="footer-bottom"><span>© 2026 Kumar Aman</span><span>Built independently from the reference design system.</span></div></footer>`}
function projectCard(p,i){return `<article class="project-card" data-route="/work/${p.slug}"><div class="project-art tone-${p.tone}"><span>${String(i+1).padStart(2,'0')}</span><em>${esc(p.title)}</em></div><div class="project-meta"><div><h2>${esc(p.title)}</h2><p>${esc(p.client)}</p></div><div class="project-discipline">${esc(p.discipline)}</div><span class="project-arrow">↗</span></div></article>`}
function home(){return `${header()}<main>
<section class="hero"><div class="hero-inner"><div class="hero-kicker">Hello!</div><div class="hero-title">I'm Kumar Aman,<br><span>a creative director.</span></div><p class="hero-copy">Creative direction for brands, campaigns and cultural storytelling across film, design and digital media.</p><div class="hero-tags"><span>Brand</span><span>Film</span><span>Motion</span><span>Digital</span></div></div></section>
<section class="intro-cards"><div class="cards-grid"><a class="info-card lavender" href="#work"><span class="card-arrow">↗</span><h3>My Work</h3><p>A curated selection of brand campaigns, films and visual systems.</p></a><a class="info-card white" href="#about"><span class="card-arrow">↗</span><h3>About Me</h3><p>A closer look at the practice, experience and thinking behind the work.</p></a><a class="info-card peach" href="#contact"><span class="card-arrow">↗</span><h3>Contact Me</h3><p>Open for selected collaborations and creative leadership work.</p></a></div></section>
<section id="work" class="section work-section"><div class="section-inner narrow"><div class="section-heading"><h2>My selected work</h2><p>A curated selection of brand campaigns, films and visual systems exploring storytelling through design and cinematic language.</p></div><div class="project-list">${projects.map(projectCard).join('')}</div><div class="center"><a class="pill" href="/work">See all work <span>↗</span></a></div></div></section>
<section class="testimonial"><div class="testimonial-inner"><blockquote>“Kumar brings cinematic clarity to brand storytelling. His direction balances visual craft with strategic thinking, resulting in campaigns that resonate deeply.”</blockquote><div class="testimonial-meta"><strong>Creative Lead</strong><span>Global Brand Campaign</span></div></div></section>
<section id="experience" class="section process-section"><div class="section-inner"><div class="section-heading"><h2>High-quality work with real value considered.</h2><p>My working process moves from understanding to direction, execution and refinement, keeping clarity at the centre of the work.</p></div><div class="process-grid">${process.map(([n,t,d])=>`<article class="process-item"><span>${n}</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></div></section>
<section class="section facts-section"><div class="section-inner"><div class="section-heading"><h2>The work says it all.</h2><p>Experience and consistency built across years of making identities, campaigns, films and digital experiences.</p></div><div class="facts-grid"><div><b>500+</b><span>Projects</span></div><div><b>6+</b><span>Years in practice</span></div><div><b>MTV</b><span>India feature</span></div><div><b>ELLE</b><span>India publication</span></div><div><b>01</b><span>Independent creative practice</span></div></div></div></section>
<section id="about" class="section about-section"><div class="section-inner about-grid"><div class="about-mark">K<br>A</div><div class="about-copy"><h2>Hey! That's me.</h2><p>I work across brand, design, motion and film, moving between strategy and execution until the idea has a visual language of its own.</p><p>From a logo system to a campaign, a website to a cinematic film, the medium changes. The obsession with making it feel right does not.</p><div class="about-details"><span>Creative Director</span><span>Designer</span><span>Filmmaker</span><span>India · Worldwide</span></div></div></div></section>
<section class="section capabilities-section"><div class="section-inner"><div class="section-heading"><h2>My capabilities</h2><p>The services I bring together across strategy, identity, digital, motion and production.</p></div><div class="capabilities">${capabilities.map((c,i)=>`<div class="capability"><span>0${i+1}</span><h3>${c}</h3></div>`).join('')}</div></div></section>
<section class="section blog-section"><div class="section-inner narrow"><div class="section-heading"><h2>From the practice</h2><p>Notes on creative direction, design systems, visual storytelling and making work that lasts.</p></div><div class="notes"><article><span>01</span><h3>Ideas made visible.</h3><p>Brand worlds, digital experiences, films and visual systems for people building something worth remembering.</p></article><article><span>02</span><h3>Built with intention.</h3><p>A practice moving between strategy and execution until the idea has a language of its own.</p></article></div></div></section>
<section id="contact" class="contact-section"><div class="contact-inner"><h2>Let's talk about your project.</h2><p>Have a problem worth solving? Let's create something considered, useful and memorable.</p><a class="contact-link" href="mailto:madebykraman@gmail.com">madebykraman@gmail.com <span>↗</span></a><div class="contact-footer"><span>Open for selected collaborations</span><div>${socials.map(([n,u])=>`<a href="${u}" target="_blank" rel="noreferrer">${n}</a>`).join('')}</div></div></div></section>
</main>${footer()}`}
function work(){return `${header()}<main><section class="page-hero"><div><span>Selected work</span><h1>Some of my favourite work.</h1></div></section><section class="section"><div class="section-inner narrow"><div class="project-list">${projects.map(projectCard).join('')}</div></div></section></main>${footer()}`}
function projectPage(p){return `${header()}<main><section class="project-hero tone-${p.tone}"><div><span>0${projects.indexOf(p)+1} / Selected work</span><h1>${esc(p.title)}</h1><p>${esc(p.client)}</p></div></section><section class="section"><div class="section-inner project-detail"><div><span class="eyebrow">Project</span><h2>${esc(p.discipline)}</h2></div><p>A selected project from Kumar Aman’s creative direction practice. The supplied content site identifies this work and client but does not expose a downloadable case-study asset or project detail page, so no unsupported project facts are invented here.</p><div class="project-placeholder"><span>${esc(p.title)}</span><small>Project imagery and case-study media are omitted because the supplied content source does not expose downloadable project assets.</small></div><a class="back-link" href="/work">← Back to work</a></div></section></main>${footer()}`}
function render(){const path=window.location.pathname.replace(/\/$/,'')||'/';const p=projects.find(x=>path.startsWith('/work/')&&path.slice(6)===x.slug);app.innerHTML=p?projectPage(p):path==='/work'?work():home();document.title=p?`${p.title} | Kumar Aman`:path==='/work'?'Work | Kumar Aman':'Kumar Aman | Creative Director & Filmmaker';bind()}
function bind(){document.querySelectorAll('.project-card').forEach(el=>el.addEventListener('click',()=>{history.pushState({},'',el.dataset.route);render();window.scrollTo(0,0)}));const menu=document.querySelector('.menu-btn'),panel=document.querySelector('.mobile-menu');if(menu){menu.addEventListener('click',()=>{const open=panel.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Close':'Menu'});panel.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{panel.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menu'}))}}
window.addEventListener('popstate',()=>{render();window.scrollTo(0,0)});render()
